name: Build Images

# Déclenche le workflow à chaque push sur main
on:
  push:
    branches:
      - feature/docker-compose-erwan
      
jobs:
  build-docker-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image Backend
        working-directory: ./backend
        run: docker build -t boutique-backend .

      - name: Build Image Frontend
        working-directory: ./frontend
        run: docker build -t boutique-frontend .

