name: Build Images

# Déclenche le workflow à chaque push sur main
on:
  push:
    branches:
      - feature/docker-compose-erwan
      
      
jobs:
  build-docker-backend:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout du code 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cd Backend
        run: cd backend
        
        
      -name: Build Image Backend
        run: docker build -t boutique-backend .
        
      -name: Cd Frontend
	run: ../frontend
	
      -name: Build Image Frontend      
	run: docker build -t boutique-frontend .  
      
